# -*- coding: utf-8 -*-
"""Sumedh_Quick_Commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qN1-zycHDHbpSWzh6IxsSRZgNXNUGB4a
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("quick_commerce_with_target.csv")
df.head()

df.shape
df.info()
df.describe()

df.isnull().sum()

df.drop_duplicates(inplace=True)

df.drop("Order_ID", axis=1, inplace=True)

for val in [0,1]:
    data = df[df['Fast_Delivery']==val]['Delivery_Time_Min']
    plt.hist(data, bins=30, density=True, alpha=0.6, label=f'Class {val}')
plt.legend()
plt.title("Delivery Time Distribution")
plt.show()

import numpy as np

groups = [df[df['Fast_Delivery']==0]['Distance_Km'],
          df[df['Fast_Delivery']==1]['Distance_Km']]

plt.boxplot(groups)

for i, g in enumerate(groups, start=1):
    x = np.random.normal(i, 0.04, size=len(g))
    plt.plot(x, g, 'o', alpha=0.2)

plt.title("Distance vs Fast Delivery")
plt.show()

x = df['Distance_Km']
y = df['Delivery_Time_Min']

plt.scatter(x, y, alpha=0.4)

m, b = np.polyfit(x, y, 1)
plt.plot(x, m*x + b)

plt.title("Distance vs Delivery Time")
plt.show()

corr = df.select_dtypes(include=np.number).corr()

plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=45)
plt.yticks(range(len(corr.columns)), corr.columns)

for i in range(len(corr)):
    for j in range(len(corr)):
        plt.text(j, i, f"{corr.iloc[i,j]:.2f}", ha='center', va='center', fontsize=6)

plt.title("Correlation Matrix")
plt.show()

import seaborn as sns

sns.kdeplot(data=df, x="Delivery_Time_Min", hue="Fast_Delivery", fill=True)
plt.title("Density Distribution of Delivery Time")
plt.show()

city_rate = df.groupby('City')['Fast_Delivery'].mean().sort_values()

city_rate.plot(kind='barh')
plt.title("Fast Delivery Rate by City")
plt.show()

df_sorted = df.sort_values("Distance_Km")

plt.plot(df_sorted["Distance_Km"], df_sorted["Delivery_Time_Min"])
plt.title("Trend of Delivery Time with Distance")
plt.show()

sns.swarmplot(data=df.sample(500), x="Fast_Delivery", y="Distance_Km")
plt.title("Distance Spread by Delivery Type")
plt.show()

df = pd.get_dummies(df, drop_first=True)

X = df.drop("Fast_Delivery", axis=1)
y = df["Fast_Delivery"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_estimator(rf, X_test, y_test)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

importances = rf.feature_importances_
features = X.columns

indices = np.argsort(importances)

plt.figure(figsize=(8,6))
plt.barh(range(len(indices)), importances[indices])
plt.yticks(range(len(indices)), [features[i] for i in indices])
plt.title("Feature Importance (Random Forest)")
plt.xlabel("Importance")
plt.show()